const ENGLISH_STOPWORDS: string[] = [
  // Core English stopwords and filler terms frequently appearing in metadata
  'about','above','across','after','again','against','along','almost','alone','already','also','although','always','among','an','and','another',
  'any','anyone','anything','anywhere','are','around','because','become','becomes','becoming','been','before','behind','being','below','between',
  'beyond','both','but','came','can','cannot','cant','come','comes','could','couldnt','describe','described','did','didnt','does','doesnt','doing',
  'done','during','each','either','else','elsewhere','enough','every','everyone','everything','everywhere','few','fewer','first','former','formerly',
  'forth','from','further','furthermore','had','hadnt','happen','happened','happening','happens','hardly','has','hasnt','have','havent','having',
  'here','hereafter','hereby','herein','hereupon','hers','herself','him','himself','his','however','into','its','itself','just','keep','keeps','kept',
  'last','later','least','less','ll','made','make','makes','many','maybe','mean','means','meant','might','mine','more','moreover','mostly','must',
  'myself','near','nearly','need','needs','neither','never','nevertheless','next','none','nonetheless','nor','not','nothing','now','nowhere','often',
  'once','one','ones','only','onto','other','others','otherwise','our','ours','ourselves','out','over','overall','own','part','perhaps','place',
  'places','please','put','puts','rather','really','said','same','say','says','see','seem','seemed','seeming','seems','seen','sees','several','shall',
  'should','shouldnt','since','some','somehow','someone','something','sometime','sometimes','somewhere','soon','such','take','taken','taking','than',
  'that','thats','their','theirs','them','themselves','then','there','thereafter','thereby','therefore','therein','thereupon','these','they','thing',
  'things','think','thinks','those','though','through','throughout','thus','together','too','toward','towards','under','until','upon','used','using',
  'various','very','want','wants','was','wasnt','well','were','werent','what','whatever','when','whenever','where','whereas','wherein','whereupon',
  'wherever','whether','which','while','whither','who','whoever','whole','whom','whose','why','will','with','within','without','wont','would','yet',
  'you','your','yours','yourself','yourselves',
  // Additional product, marketing, and documentation filler terms
  'able','abstract','access','according','acquired','actionable','active','activities','actual','actually','additional','address','advanced',
  'affected','affecting','agency','agenda','agreement','ahead','alert','allow','allows','alongside','amount','analysis','announce','announced',
  'announcement','annual','answer','applied','apply','approach','appropriate','approval','archive','article','aspect','assess','asset','associated',
  'association','assumption','attached','author','available','average','awesome','background','based','basic','basics','becoming','begin','beginning',
  'behind','benefit','best','better','beyond','biggest','blog','blogs','board','bonus','book','brief','broad','building','built','business','buying',
  'calendar','call','called','calling','campaign','capital','careers','case','cases','catch','catalog','category','causes','central','challenge',
  'challenges','change','changes','channel','check','checked','checking','checkout','choose','choosing','classic','clear','clearly','client','clients',
  'close','closed','closing','codebase','collective','coming','comment','comments','commit','common','community','company','complete','completed',
  'completely','complex','component','concept','concern','concerns','concerning','conclusion','conditions','conference','consent','consider',
  'considered','consists','constant','consulting','contact','content','continue','continued','continues','contract','contribution','control',
  'conversation','copy','corporate','correct','cost','couldn','count','countries','cover','covered','covering','create','created','creating','creation',
  'creative','creator','credit','current','currently','customer','customers','daily','dashboard','data','dear','decision','decisions','declared',
  'default','delivery','demand','department','deploy','deployment','describe','design','designed','details','develop','developed','developer',
  'developers','developing','development','device','difference','different','digital','direct','direction','discover','discuss','discussion','display',
  'document','documentation','documents','doesn','doing','dollar','domain','download','draft','early','edition','effective','efficient','effort',
  'email','employee','employees','enabled','encourage','endless','engage','engaged','engagement','engineer','engineering','enjoy','enough','ensure',
  'ensuring','enterprise','entry','environment','especially','essential','established','estimate','event','events','everyday','everyone','example',
  'excellent','except','exciting','executive','existing','expand','expect','experience','experienced','expert','experts','explore','exploring',
  'external','feature','features','feedback','figure','final','finally','finished','follow','following','follows','footnote','format','former',
  'forward','framework','free','frequently','friendly','full','fully','fund','future','general','generate','generated','generic','global','goal',
  'goals','going','great','group','guide','guides','handle','happens','happy','header','help','helpful','helping','helps','highlight','highlights',
  'homepage','however','https','http','impact','important','improve','improved','improving','inclusive','increase','increased','indicate','information',
  'initial','initiative','innovative','insight','insights','inside','installation','installing','instead','instruction','instructions','integrate',
  'integrated','integration','introduction','item','items','join','joined','journey','keep','keeping','keynote','knowledge','later','latest','launch',
  'launched','learning','lessons','letter','library','likely','limited','list','listed','listing','lists','local','location','longer','looking','main',
  'major','management','manager','market','marketing','master','meaning','means','media','member','members','message','messages','method','methods',
  'metrics','might','mind','minutes','model','models','moment','money','month','monthly','months','mostly','move','moved','moving','multiple','must',
  'named','navigation','need','needed','network','news','newsletter','normal','notice','objective','office','official','often','online','opens',
  'option','options','order','ordered','orders','organization','original','overview','owner','owners','package','page','pages','panel','paper',
  'particular','partner','partnership','password','pattern','patterns','performance','personal','phone','photo','photos','piece','plan','planned',
  'platform','please','plugin','popular','portfolio','position','post','posted','posting','posts','practice','practices','premium','prepare',
  'prepared','present','presentation','presented','press','preview','previous','primary','principles','prior','priority','private','problem','process',
  'produce','product','production','products','program','programs','project','projects','prompt','published','purpose','quality','quick','quickly',
  'read','reader','readers','reading','ready','really','recent','recently','recommended','record','release','released','relevance','remain','remember',
  'reminder','remote','report','reporting','reports','require','required','requirements','requires','research','resource','resources','response',
  'result','results','review','role','sales','sample','scheduled','screenshot','section','select','selected','selection','series','service','services',
  'setting','settings','share','shared','sharing','shop','sign','significant','signs','simple','simply','slightly','solution','solutions','source',
  'sources','space','specific','specifically','specs','sponsored','standard','start','started','starting','state','statement','steps','stories','story',
  'stream','structure','student','students','studio','style','subject','subscribe','successful','summary','support','supported','supporting','system',
  'systems','table','takeaway','task','team','teams','technical','technologies','technology','template','templates','terms','text','thanks','theme',
  'thing','things','think','thought','thoughts','thread','throughout','tool','tools','topic','topics','total','tour','track','tracking','training',
  'trend','trends','tutorial','type','types','understand','understanding','update','updates','upgrade','upload','usage','useful','user','users','using',
  'value','version','video','videos','visit','visual','wait','waiting','watch','webinar','website','weekly','welcome','went','whether','whitepaper',
  'whole','wide','widely','win','without','wonderful','work','worked','working','workflow','world','writing','written'
];

const RUSSIAN_STOPWORDS: string[] = [
  // Common Russian stopwords (spread across parts of speech)
  'и','в','во','не','что','он','она','они','как','из','у','за','для','по','к','ко','на','но','а','же','ли','или','ни','да','нет','так','то','же',
  'это','его','её','ее','их','еею','меня','мне','мной','мы','нам','нами','вы','вам','вами','ты','тебя','тебе','тобой','тот','та','те','тем','таким',
  'такая','такой','эти','этот','эта','этом','этих','эту','этому','будет','бы','был','была','были','быть','есть','нету','есть','будут','будто','если',
  'когда','тогда','потом','потому','затем','чтобы','чтоб','чему','чем','чего','чей','через','нею','нее','неею','нему','ним','них','без','более','менее',
  'почти','сразу','просто','порой','кстати','всегда','никогда','вновь','снова','ранее','позже','сейчас','теперь','уже','еще','ещё','также','тоже',
  'кроме','между','среди','около','рядом','там','здесь','сюда','туда','отсюда','оттуда','везде','повсюду','должен','должна','должны','может','можно',
  'нужно','нужен','нужна','нужны','сам','сама','само','самой','самим','самих','самому','самим','самих','самыми','свой','своя','свои','своё','своей',
  'своему','своим','своих','своими','каждый','каждая','каждое','каждые','каждого','каждой','каждому','каждым','каждых','лишь','уже','всё','все','всю',
  'всех','всем','всеми','всему','нихто','ничто','некто','некто','некого','некому','ничего','никто','никого','никому','никуда','никуда','зато','зато',
  'зачем','почему','потому','впрочем','однако','иначе','раньше','пока','покуда','ведь','ибо','разве','уж','уж-то','уже','ещё','как-то','кое-кто',
  'кое-что','всё-таки','поэтому','вследствие','наверно','наверное','видимо','похоже','почем','замечено','бывает','бывало','быстро','сильно','совсем',
  'слишком','совершенно','довольно','достаточно','необходимо','невозможно','нельзя','различных','разный','разная','разные','разного','разной','разному',
  'разных','чуть','чуть-чуть','либо','толи','то ли','хотя','хоть','хочет','хотят','хотим','хочу','хочешь','хочет','было','будем','будешь','будут'
];

export const TAG_STOPWORDS = new Set<string>([
  ...ENGLISH_STOPWORDS,
  ...RUSSIAN_STOPWORDS
]);

