export const TAG_SYNONYM_MAP: Record<string, string> = {
  // English technical domains
  ai: 'artificial-intelligence',
  'a.i.': 'artificial-intelligence',
  'artificial intelligence': 'artificial-intelligence',
  'artificialintelligence': 'artificial-intelligence',
  'artificial-intelligence': 'artificial-intelligence',
  ml: 'machine-learning',
  'machine learning': 'machine-learning',
  'machinelearning': 'machine-learning',
  'machine-learning': 'machine-learning',
  deeplearning: 'deep-learning',
  'deep learning': 'deep-learning',
  'deep-learning': 'deep-learning',
  nlp: 'natural-language-processing',
  'natural language processing': 'natural-language-processing',
  'natural-language-processing': 'natural-language-processing',
  gpt: 'generative-ai',
  'large-language-model': 'generative-ai',
  llm: 'generative-ai',
  'large language model': 'generative-ai',
  robotic: 'robotics',
  robots: 'robotics',
  robot: 'robotics',
  robotics: 'robotics',
  automation: 'process-automation',
  'process automation': 'process-automation',
  rpa: 'process-automation',
  'process-automation': 'process-automation',
  js: 'javascript',
  javascript: 'javascript',
  'node.js': 'nodejs',
  nodejs: 'nodejs',
  node: 'nodejs',
  npm: 'nodejs',
  webpack: 'javascript-tooling',
  'javascript tooling': 'javascript-tooling',
  typescript: 'typescript',
  ts: 'typescript',
  'type script': 'typescript',
  deno: 'javascript-runtime',
  'javascript runtime': 'javascript-runtime',
  react: 'reactjs',
  'react.js': 'reactjs',
  'react-js': 'reactjs',
  'react native': 'react-native',
  reactnative: 'react-native',
  redux: 'reactjs',
  hooks: 'reactjs',
  vue: 'vuejs',
  'vue.js': 'vuejs',
  'vue-js': 'vuejs',
  nuxt: 'vuejs',
  angular: 'angularjs',
  'angular.js': 'angularjs',
  svelte: 'sveltejs',
  'svelte.js': 'sveltejs',
  solid: 'solidjs',
  'solid.js': 'solidjs',
  astro: 'astrojs',
  'astro.js': 'astrojs',
  next: 'nextjs',
  'next.js': 'nextjs',
  'next-js': 'nextjs',
  remix: 'remixjs',
  'remix.run': 'remixjs',
  gatsby: 'gatsbyjs',
  'gatsby.js': 'gatsbyjs',
  lit: 'litjs',
  'lit-element': 'litjs',
  jquery: 'jqueryjs',
  backbone: 'backbonejs',
  'backbone.js': 'backbonejs',
  ember: 'emberjs',
  'ember.js': 'emberjs',
  express: 'expressjs',
  'express.js': 'expressjs',
  koa: 'koajs',
  'koa.js': 'koajs',
  hapi: 'hapijs',
  'hapi.js': 'hapijs',
  fastify: 'fastifyjs',
  nest: 'nestjs',
  'nest.js': 'nestjs',
  graphql: 'graph-ql',
  'graph ql': 'graph-ql',
  apollo: 'graph-ql',
  relay: 'graph-ql',
  rest: 'rest-api',
  'rest api': 'rest-api',
  restful: 'rest-api',
  grpc: 'grpc',
  protobuf: 'grpc',
  websocket: 'real-time',
  websockets: 'real-time',
  realtime: 'real-time',
  'real time': 'real-time',
  webgl: 'web-graphics',
  'web gl': 'web-graphics',
  wasm: 'webassembly',
  'web assembly': 'webassembly',
  webassembly: 'webassembly',
  html: 'html5',
  html5: 'html5',
  css: 'css3',
  css3: 'css3',
  scss: 'css3',
  sass: 'css3',
  less: 'css3',
  tailwind: 'tailwindcss',
  'tailwind css': 'tailwindcss',
  bootstrap: 'bootstrapcss',
  foundation: 'foundationcss',
  bulma: 'bulmacss',
  materialize: 'material-design',
  'material design': 'material-design',
  materialui: 'material-design',
  mui: 'material-design',
  chakra: 'chakrau',
  'chakra ui': 'chakrau',
  daisyui: 'daisyui',
  storybook: 'storybookjs',
  jest: 'jestjs',
  testinglibrary: 'testing-library',
  'testing-library': 'testing-library',
  mocha: 'mochajs',
  chai: 'mochajs',
  sinon: 'mochajs',
  vitest: 'vitestjs',
  cypress: 'cypress-testing',
  playwright: 'playwright-testing',
  selenium: 'selenium-testing',
  webdriver: 'selenium-testing',
  puppeteer: 'puppeteer-testing',
  pytest: 'python-testing',
  unittest: 'python-testing',
  nose: 'python-testing',
  python2: 'python',
  python3: 'python',
  py: 'python',
  pip: 'python',
  django: 'django-framework',
  flask: 'flask-framework',
  fastapi: 'fastapi-framework',
  tornado: 'tornado-framework',
  bottle: 'bottle-framework',
  sqlalchemy: 'python-orm',
  pandas: 'data-analysis',
  numpy: 'data-analysis',
  scipy: 'data-analysis',
  matplotlib: 'data-visualization',
  seaborn: 'data-visualization',
  plotly: 'data-visualization',
  jupyter: 'jupyter-notebook',
  'jupyter notebook': 'jupyter-notebook',
  ipynb: 'jupyter-notebook',
  rstudio: 'r-programming',
  tidyverse: 'r-programming',
  spark: 'apache-spark',
  pyspark: 'apache-spark',
  scala: 'scala-lang',
  'scala.js': 'scalajs',
  scikitlearn: 'scikit-learn',
  'scikit learn': 'scikit-learn',
  tensorflow: 'tensorflow-ml',
  keras: 'tensorflow-ml',
  pytorch: 'pytorch-ml',
  torch: 'pytorch-ml',
  opencv: 'computer-vision',
  'computer vision': 'computer-vision',
  cv: 'computer-vision',
  gan: 'generative-ai',
  diffusion: 'generative-ai',
  'stable diffusion': 'generative-ai',
  docker: 'containers',
  container: 'containers',
  containers: 'containers',
  kubernetes: 'kubernetes',
  k8s: 'kubernetes',
  helm: 'kubernetes',
  istio: 'service-mesh',
  linkerd: 'service-mesh',
  envoy: 'service-mesh',
  terraform: 'terraform-iac',
  pulumi: 'infrastructure-as-code',
  'infrastructure as code': 'infrastructure-as-code',
  ansible: 'configuration-management',
  chef: 'configuration-management',
  puppet: 'configuration-management',
  salt: 'configuration-management',
  nomad: 'hashicorp-nomad',
  vault: 'hashicorp-vault',
  consul: 'hashicorp-consul',
  ecs: 'aws-containers',
  eks: 'aws-containers',
  fargate: 'aws-containers',
  lambda: 'serverless',
  serverless: 'serverless',
  faas: 'serverless',
  cloudfunctions: 'serverless',
  cloudrun: 'serverless',
  gke: 'gcp-containers',
  gcs: 'google-cloud-storage',
  s3: 'aws-s3',
  dynamodb: 'aws-dynamodb',
  firestore: 'firebase-firestore',
  firebase: 'firebase-platform',
  'firebase hosting': 'firebase-platform',
  amplify: 'aws-amplify',
  supabase: 'supabase-platform',
  planetscale: 'mysql',
  'planet scale': 'mysql',
  mysql: 'mysql',
  mariadb: 'mysql',
  postgres: 'postgresql',
  postgresql: 'postgresql',
  postgis: 'postgresql',
  cockroachdb: 'distributed-sql',
  tidb: 'distributed-sql',
  sqlite: 'sqlite',
  mongodb: 'mongodb',
  'mongo db': 'mongodb',
  atlas: 'mongodb',
  redis: 'redis',
  memcached: 'cache',
  cassandra: 'apache-cassandra',
  elasticsearch: 'elasticsearch',
  'elastic search': 'elasticsearch',
  opensearch: 'elasticsearch',
  logstash: 'elk-stack',
  kibana: 'elk-stack',
  grafana: 'observability',
  prometheus: 'observability',
  influxdb: 'observability',
  datadog: 'observability',
  newrelic: 'observability',
  splunk: 'log-management',
  honeycomb: 'observability',
  jaeger: 'distributed-tracing',
  zipkin: 'distributed-tracing',
  'open telemetry': 'distributed-tracing',
  opentelemetry: 'distributed-tracing',
  sre: 'site-reliability-engineering',
  devops: 'devops',
  'dev ops': 'devops',
  cicd: 'ci-cd',
  'ci/cd': 'ci-cd',
  githubactions: 'ci-cd',
  gitlabci: 'ci-cd',
  travisci: 'ci-cd',
  circleci: 'ci-cd',
  jenkins: 'ci-cd',
  teamcity: 'ci-cd',
  azuredevops: 'ci-cd',
  'azure devops': 'ci-cd',
  bitbucket: 'bitbucket',
  'bitbucket pipelines': 'ci-cd',
  gitops: 'gitops',
  argo: 'gitops',
  'argo cd': 'gitops',
  flux: 'gitops',
  observability: 'observability',
  oncall: 'site-reliability-engineering',
  pagerduty: 'incident-response',
  opsgenie: 'incident-response',
  xmatters: 'incident-response',
  incident: 'incident-response',
  incidentresponse: 'incident-response',
  qa: 'quality-assurance',
  quality: 'quality-assurance',
  shiftleft: 'application-security',
  'shift left': 'application-security',
  security: 'application-security',
  secops: 'security-operations',
  devsecops: 'application-security',
  appsec: 'application-security',
  pentest: 'penetration-testing',
  ctf: 'penetration-testing',
  vulnerabilities: 'application-security',
  vuln: 'application-security',
  threat: 'threat-detection',
  'threat detection': 'threat-detection',
  detection: 'threat-detection',
  compliance: 'governance-risk-compliance',
  gdpr: 'privacy',
  hipaa: 'privacy',
  soc2: 'governance-risk-compliance',
  pci: 'governance-risk-compliance',
  zerotrust: 'zero-trust-security',
  'zero trust': 'zero-trust-security',
  oauth: 'identity-management',
  oidc: 'identity-management',
  saml: 'identity-management',
  'single sign on': 'identity-management',
  'single-sign-on': 'identity-management',
  sso: 'identity-management',
  iam: 'identity-management',
  auth: 'identity-management',
  authentication: 'identity-management',
  authorization: 'identity-management',
  login: 'identity-management',
  signup: 'identity-management',
  'two-factor': 'multi-factor-authentication',
  '2fa': 'multi-factor-authentication',
  mfa: 'multi-factor-authentication',
  biometrics: 'identity-management',
  passwordless: 'identity-management',
  oauth2: 'identity-management',
  apikeys: 'identity-management',
  certificates: 'identity-management',
  blockchain: 'blockchain',
  'crypto currency': 'cryptocurrency',
  cryptocurrency: 'cryptocurrency',
  crypto: 'cryptocurrency',
  defi: 'decentralized-finance',
  web3: 'web3',
  nft: 'nfts',
  nfts: 'nfts',
  metaverse: 'metaverse',
  smartcontract: 'smart-contracts',
  'smart contract': 'smart-contracts',
  solidity: 'smart-contracts',
  rust: 'rust-lang',
  go: 'golang',
  golang: 'golang',
  'go lang': 'golang',
  elixir: 'elixir-lang',
  phoenix: 'phoenix-framework',
  erlang: 'erlang-lang',
  java: 'java',
  jvm: 'java',
  spring: 'spring-framework',
  'spring boot': 'spring-boot',
  springboot: 'spring-boot',
  quarkus: 'quarkus-framework',
  micronaut: 'micronaut-framework',
  kotlin: 'kotlin',
  groovy: 'groovy-lang',
  grails: 'groovy-lang',
  clojure: 'clojure-lang',
  clojurescript: 'clojure-lang',
  sparkjava: 'java',
  micronautframework: 'micronaut-framework',
  php: 'php',
  laravel: 'laravel-framework',
  symfony: 'symfony-framework',
  codeigniter: 'php-frameworks',
  cakephp: 'php-frameworks',
  yii: 'php-frameworks',
  wordpress: 'wordpress',
  drupal: 'drupal',
  joomla: 'joomla',
  magento: 'magento',
  shopify: 'shopify',
  bigcommerce: 'bigcommerce',
  prestashop: 'prestashop',
  opencart: 'opencart',
  umbraco: 'umbraco',
  strapi: 'headless-cms',
  contentful: 'headless-cms',
  sanity: 'headless-cms',
  ghost: 'headless-cms',
  forestry: 'headless-cms',
  netlifycms: 'headless-cms',
  'netlify cms': 'headless-cms',
  datascience: 'data-science',
  'data science': 'data-science',
  dataviz: 'data-visualization',
  datavisualization: 'data-visualization',
  analysis: 'data-analysis',
  bi: 'business-intelligence',
  'business intelligence': 'business-intelligence',
  tableau: 'business-intelligence',
  powerbi: 'business-intelligence',
  'power bi': 'business-intelligence',
  looker: 'business-intelligence',
  'data engineering': 'data-engineering',
  dataengineering: 'data-engineering',
  airflow: 'data-engineering',
  dbt: 'data-engineering',
  kafka: 'event-streaming',
  ksqldb: 'event-streaming',
  pulsar: 'event-streaming',
  rabbitmq: 'messaging-queues',
  activemq: 'messaging-queues',
  sqs: 'messaging-queues',
  sns: 'messaging-queues',
  pubsub: 'messaging-queues',
  mqtt: 'messaging-queues',
  websocketss: 'real-time',
  eventbridge: 'event-driven-architecture',
  triggered: 'event-driven-architecture',
  microservices: 'microservices',
  monolith: 'monolithic-architecture',
  'monolithic architecture': 'monolithic-architecture',
  soa: 'service-oriented-architecture',
  ddd: 'domain-driven-design',
  cqrs: 'cqrs-pattern',
  eventsource: 'event-sourcing',
  'event sourcing': 'event-sourcing',
  tdd: 'test-driven-development',
  bdd: 'behavior-driven-development',
  'behaviour driven': 'behavior-driven-development',
  pairprogramming: 'pair-programming',
  'pair programming': 'pair-programming',
  mobprogramming: 'mob-programming',
  refactor: 'refactoring',
  refactoring: 'refactoring',
  'tech debt': 'technical-debt',
  techdebt: 'technical-debt',
  codequality: 'code-quality',
  cleanarchitecture: 'clean-architecture',
  'clean architecture': 'clean-architecture',
  solidprinciples: 'solid-principles',
  'solid principles': 'solid-principles',
  dry: 'software-principles',
  kiss: 'software-principles',
  yagni: 'software-principles',
  ux: 'user-experience',
  'user experience': 'user-experience',
  userexperience: 'user-experience',
  ui: 'user-interface',
  'user interface': 'user-interface',
  userinterface: 'user-interface',
  cx: 'customer-experience',
  'customer experience': 'customer-experience',
  servicedesign: 'service-design',
  'service design': 'service-design',
  designops: 'design-operations',
  researchops: 'research-operations',
  ahaa: 'design-thinking',
  designthinking: 'design-thinking',
  'design thinking': 'design-thinking',
  wireframe: 'wireframing',
  wireframing: 'wireframing',
  uxresearch: 'ux-research',
  userresearch: 'ux-research',
  uiux: 'user-interface',
  figma: 'design-tools',
  sketch: 'design-tools',
  invision: 'design-tools',
  adobexd: 'design-tools',
  'adobe xd': 'design-tools',
  xd: 'design-tools',
  photoshop: 'design-tools',
  illustrator: 'design-tools',
  canva: 'design-tools',
  procreate: 'design-tools',
  blender: '3d-design',
  '3d': '3d-design',
  '3d design': '3d-design',
  cad: 'cad-design',
  fusion360: 'cad-design',
  solidworks: 'cad-design',
  catia: 'cad-design',
  inventor: 'cad-design',
  rhino: 'cad-design',
  architecture: 'software-architecture',
  'software architecture': 'software-architecture',
  enterprise: 'enterprise-architecture',
  'enterprise architecture': 'enterprise-architecture',
  business: 'business',
  startup: 'startups',
  startups: 'startups',
  entrepreneur: 'entrepreneurship',
  entrepreneurship: 'entrepreneurship',
  founder: 'entrepreneurship',
  founders: 'entrepreneurship',
  pitch: 'pitching',
  fundraising: 'fundraising',
  fundraise: 'fundraising',
  investors: 'investing',
  venture: 'venture-capital',
  'venture capital': 'venture-capital',
  vc: 'venture-capital',
  angel: 'angel-investing',
  financing: 'fundraising',
  bootstrapping: 'bootstrapping',
  accelerator: 'accelerators',
  incubator: 'incubators',
  growth: 'growth-marketing',
  marketing: 'marketing',
  productmarketing: 'product-marketing',
  'product marketing': 'product-marketing',
  product: 'product-management',
  'product management': 'product-management',
  productmanager: 'product-management',
  pm: 'product-management',
  roadmap: 'product-management',
  backlog: 'product-management',
  agile: 'agile-methodology',
  scrum: 'agile-methodology',
  kanban: 'agile-methodology',
  lean: 'lean-methodology',
  okr: 'objectives-key-results',
  okrs: 'objectives-key-results',
  'key results': 'objectives-key-results',
  kpi: 'key-performance-indicators',
  kpis: 'key-performance-indicators',
  metric: 'key-performance-indicators',
  analytics: 'data-analysis',
  'customer success': 'customer-success',
  customersuccess: 'customer-success',
  csat: 'customer-satisfaction',
  nps: 'customer-satisfaction',
  churn: 'customer-retention',
  retention: 'customer-retention',
  growthhack: 'growth-hacking',
  'growth hack': 'growth-hacking',
  marketingops: 'marketing-operations',
  revenue: 'revenue-operations',
  revops: 'revenue-operations',
  sales: 'sales',
  presales: 'sales-engineering',
  'pre sales': 'sales-engineering',
  pipeline: 'sales-operations',
  crm: 'customer-relationship-management',
  'customer relationship management': 'customer-relationship-management',
  hubspot: 'customer-relationship-management',
  salesforce: 'customer-relationship-management',
  zoho: 'customer-relationship-management',
  sap: 'enterprise-software',
  oracle: 'enterprise-software',
  netsuite: 'enterprise-software',
  'microsoft dynamics': 'enterprise-software',
  erp: 'enterprise-resource-planning',
  hr: 'human-resources',
  'human resources': 'human-resources',
  peopleops: 'people-operations',
  'people ops': 'people-operations',
  recruiting: 'talent-acquisition',
  talent: 'talent-acquisition',
  'talent acquisition': 'talent-acquisition',
  hiring: 'talent-acquisition',
  onboarding: 'employee-onboarding',
  offboarding: 'employee-experience',
  benefits: 'employee-benefits',
  compensation: 'employee-compensation',
  payroll: 'payroll-management',
  performance: 'performance-management',
  review: 'performance-management',
  coaching: 'people-development',
  mentorship: 'people-development',
  leadership: 'leadership',
  management: 'management',
  manager: 'management',
  teamwork: 'team-collaboration',
  collaboration: 'team-collaboration',
  communication: 'communication',
  remote: 'remote-work',
  'remote work': 'remote-work',
  distributed: 'distributed-teams',
  async: 'asynchronous-work',
  hybrid: 'hybrid-work',
  wellbeing: 'employee-wellbeing',
  burnout: 'employee-wellbeing',
  culture: 'company-culture',
  values: 'company-values',
  inclusion: 'diversity-equity-inclusion',
  diversity: 'diversity-equity-inclusion',
  equity: 'diversity-equity-inclusion',
  belonging: 'diversity-equity-inclusion',
  dei: 'diversity-equity-inclusion',
  accessibility: 'accessibility',
  a11y: 'accessibility',
  seo: 'search-engine-optimization',
  'search engine optimization': 'search-engine-optimization',
  'search marketing': 'search-marketing',
  sem: 'search-marketing',
  ppc: 'search-marketing',
  paidsearch: 'search-marketing',
  'paid search': 'search-marketing',
  cpc: 'search-marketing',
  serp: 'search-engine-optimization',
  keywords: 'search-engine-optimization',
  contentmarketing: 'content-marketing',
  'content marketing': 'content-marketing',
  storytelling: 'content-marketing',
  blogging: 'content-marketing',
  podcasting: 'content-marketing',
  video: 'video-marketing',
  youtube: 'video-marketing',
  tiktok: 'video-marketing',
  instagram: 'social-media-marketing',
  linkedin: 'social-media-marketing',
  twitter: 'social-media-marketing',
  facebook: 'social-media-marketing',
  snap: 'social-media-marketing',
  social: 'social-media-marketing',
  influencer: 'influencer-marketing',
  emailmarketing: 'email-marketing',
  'email marketing': 'email-marketing',
  newsletter: 'email-marketing',
  drip: 'email-marketing',
  automationmarketing: 'marketing-automation',
  hubspotmarketing: 'marketing-automation',
  segmentation: 'marketing-automation',
  personalization: 'marketing-automation',
  abtesting: 'a-b-testing',
  'a/b testing': 'a-b-testing',
  experiments: 'a-b-testing',
  optimization: 'conversion-optimization',
  conversion: 'conversion-optimization',
  attribution: 'marketing-attribution',
  martech: 'marketing-technology',
  adtech: 'ad-technology',
  branding: 'brand-strategy',
  brand: 'brand-strategy',
  positioning: 'brand-strategy',
  messaging: 'brand-strategy',
  pr: 'public-relations',
  publicrelations: 'public-relations',
  communications: 'public-relations',
  crisis: 'crisis-communications',

  // Russian technology and business synonyms (transliterations and Cyrillic)
  'машинное обучение': 'machine-learning',
  'глубокое обучение': 'deep-learning',
  'обработка естественного языка': 'natural-language-processing',
  'нейросети': 'neural-networks',
  'нейросеть': 'neural-networks',
  'искусственный интеллект': 'artificial-intelligence',
  'робототехника': 'robotics',
  'автоматизация процессов': 'process-automation',
  'график ql': 'graph-ql',
  'граф ql': 'graph-ql',
  'веб-assembly': 'webassembly',
  'веб сборка': 'webassembly',
  'веб-сборка': 'webassembly',
  'глубокое': 'deep-learning',
  'облачные функции': 'serverless',
  'облачные вычисления': 'cloud-computing',
  'облако': 'cloud-computing',
  'облачные сервисы': 'cloud-computing',
  'квантовые вычисления': 'quantum-computing',
  'квантовые технологии': 'quantum-computing',
  'удалённая работа': 'remote-work',
  'удаленная работа': 'remote-work',
  'дизайн-мышление': 'design-thinking',
  'пользовательский опыт': 'user-experience',
  'пользовательский интерфейс': 'user-interface',
  'цифровой маркетинг': 'digital-marketing',
  'продуктовый менеджмент': 'product-management',
  'гибкая методология': 'agile-methodology',
  'гибкие методологии': 'agile-methodology',
  'программная архитектура': 'software-architecture',
  'архитектура предприятия': 'enterprise-architecture',
  'проектное управление': 'project-management',
  'анализ данных': 'data-analysis',
  'наука о данных': 'data-science',
  'визуализация данных': 'data-visualization',
  'инженерия данных': 'data-engineering',
  'стриминг событий': 'event-streaming',
  'потоковая обработка': 'event-streaming',
  'микросервисы': 'microservices',
  'монолит': 'monolithic-architecture',
  'сервис-ориентированная архитектура': 'service-oriented-architecture',
  'доменное проектирование': 'domain-driven-design',
  'управление требованиями': 'requirements-management',
  'тестирование': 'software-testing',
  'управление качеством': 'quality-assurance',
  'инфраструктура как код': 'infrastructure-as-code',
  'администрирование систем': 'systems-administration',
  'управление конфигурацией': 'configuration-management',
  'контейнеризация': 'containers',
  'блокчейн': 'blockchain',
  'криптовалюта': 'cryptocurrency',
  'умные контракты': 'smart-contracts',
  'облачная безопасность': 'cloud-security',
  'информационная безопасность': 'application-security',
  'защита данных': 'data-security',
  'кибербезопасность': 'application-security',
  'анализ угроз': 'threat-detection',
  'реагирование на инциденты': 'incident-response',
  'управление инцидентами': 'incident-response',
  'компания': 'business',
  'стартап': 'startups',
  'предпринимательство': 'entrepreneurship',
  'привлечение инвестиций': 'fundraising',
  'венчурный капитал': 'venture-capital',
  'ангельские инвестиции': 'angel-investing',
  'развитие продукта': 'product-development',
  'рост продукта': 'growth-marketing',
  'продажи': 'sales',
  'маркетинг': 'marketing',
  'операции': 'business-operations',
  'управление персоналом': 'people-operations',
  'управление талантами': 'talent-acquisition',
  'адаптация сотрудников': 'employee-onboarding',
  'корпоративная культура': 'company-culture',
  'удержание клиентов': 'customer-retention',
  'обслуживание клиентов': 'customer-success',
  'аналитика': 'data-analysis',
  'продуктовая аналитика': 'product-analytics',
  'маркетинговая аналитика': 'marketing-analytics',
  'управление проектами': 'project-management',
  'управление продуктом': 'product-management',
  'веб-разработка': 'web-development',
  'разработка программного обеспечения': 'software-development',
  'frontend': 'frontend-development',
  'back-end': 'backend-development',
  'backend': 'backend-development',
  'fullstack': 'full-stack-development',
  'full stack': 'full-stack-development',
  'кроссфункциональные команды': 'cross-functional-teams',
  'управление изменениями': 'change-management',
  'цифровая трансформация': 'digital-transformation',
  'управление рисками': 'risk-management',
  'управление безопасностью': 'security-management',
  'оптимизация процессов': 'process-optimization',
  'планирование ресурсов': 'enterprise-resource-planning',
  'ключевые показатели': 'key-performance-indicators',
  'управление производительностью': 'performance-management'
};
